[HORN-1536] add implementation for inner-ring-bot
tomtom-international/osm-bots pull request #1
Opened 2021-11-25 14:50 UTC by LukaszStaszewski-TomTom

Add implementation for Inner Ring Bot

2021-11-26 07:03 UTC, KamilLucki-TomTom commented on bot-double-inner-ring/CODEOWNERS
> +* @tomtom-internal/osm-shinkansen
Shouldn't this file be in `.github` directory?

2021-11-26 07:25 UTC, KamilLucki-TomTom approved these changes

2021-11-26 10:44 UTC, ArkadiuszMaciaszczyk-TomTom requested changes

2021-11-26 14:26 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/ViolationsFixerConfiguration.java
> +            @NonNull @Value("${run.parameters.max-violations-per-changeset:#{null}}") Integer maxViolationsPerChangeset) {
We didn't decide on any default so far, for runs on sample region we will probably do 100, but we wanted to leave it configurable without default value.
Do you think we should put some default there which would be used in case its not specified?

2021-11-26 14:28 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/utils/Partition.java
> +public class Partition {
At first we exactly started with that guava solution, however after all we decided to write our own simple code for that (actually Maciek gave it to us for free :d) and not use guava dependency at all.
I've got mixed feelings - we have 1 less dependency now, however there is a little more code to be reviewed without guava :P

2021-11-26 14:50 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/CODEOWNERS
> +* @tomtom-internal/osm-shinkansen
removed that file completely

2021-11-26 15:04 UTC, ArkadiuszMaciaszczyk-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/ViolationsFixerConfiguration.java
> +            @NonNull @Value("${run.parameters.max-violations-per-changeset:#{null}}") Integer maxViolationsPerChangeset) {
100 sounds like good default - better than null anyway.

2021-11-26 15:28 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/ViolationsFixerConfiguration.java
> +            @NonNull @Value("${run.parameters.max-violations-per-changeset:#{null}}") Integer maxViolationsPerChangeset) {
To fast too furious - You are right we will set 100 as default

2021-11-29 08:43 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/InnerRingApplication.java
> +package osm.bots.innerringbot;
it's not *The* inner ring bot, the solution to every problem that could possibly occur on inner rings
we only solve a subset of one class of problems here: duplicated geometry

also, having multiple words as one package name is tricky, as in some cases it can be hard to read or cause misunderstandings
try to name your artifact group for the tool the same way you would name a package for a class
just imagine that instead of a single application, you're creating a whole set of related tools/libraries
```suggestion
package osm.bots.rings.inner.duplicates
```

2021-11-29 08:43 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/RunParameters.java
> +    }
```suggestion
    private Path pathToViolationsFile;
```

2021-11-29 08:48 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/changes/ChangesGenerator.java
> +    private OsmDataChange generateChange(ViolatingOsmData violatingOsmData) {
the way this class is named and located kinda gives the impression that it's just a converter to some sort of output diff format
but in fact the actual main logic of the bot is here
this should be either more exposed or better named to reflect the responsibility of this class

2021-11-29 08:49 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/FailsafeOsmFetchClient.java
> +class FailsafeOsmFetchClient {
co we have a non-failsafe client that requires this distinction in the name?
or are we naming a class after an implementation detail here?

2021-11-29 09:00 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/FailsafeOsmFetchClient.java
> +        return Failsafe.with(RetryPolicyFactory.getClientConnectionRetryPolicy())
we use retry but how about interrupting timeout?
I know we'll more likely get rejects than hangups but we've already had problems before where server performance issues literally froze the client app

2021-11-29 09:02 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/FetchConfiguration.java
> +    OsmDataFetcher getOsmDataFetcher(@NonNull @Value("${run.parameters.openstreetmap-api-url:#{null}}") String openstreetmapApiUrl) {
is `null` a valid url?
is it validated somewhere else where we'll get a nice meaningful message?

2021-11-29 09:03 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/FetchConfiguration.java
> +        OsmConnection connection = new OsmConnection(openstreetmapApiUrl, "user-agent", null);
will we ever need to change that agent?
should it be in the config?

2021-11-29 09:03 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/OsmDataFetcher.java
> +        if (violationCounter % 500 == 0) {
```suggestion
        if (++violationCounter % 500 == 0) {
```

2021-11-29 10:26 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/FetchConfiguration.java
> +    OsmDataFetcher getOsmDataFetcher(@NonNull @Value("${run.parameters.openstreetmap-api-url:#{null}}") String openstreetmapApiUrl) {
I'll remove "null" as default value, its superflous - we will still get null value if user doesn't specify it in properties and exception will be thrown anyway.

2021-11-29 10:36 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/OsmDataFetcher.java
> +        Relation osmRelation = fetchDataForRelation(violation);
renamed to fetchWays and fetchRelation

2021-11-29 11:02 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/changes/ChangesGenerator.java
> +    private OsmDataChange generateChange(ViolatingOsmData violatingOsmData) {
Hmm, I dont have any great ideas - maybe `FixGenerator.class` which would return `FixedData` object? 

I could also move it one level up to "osmapi" package to make it more exposed.

2021-11-29 11:06 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/FailsafeOsmFetchClient.java
> +class FailsafeOsmFetchClient {
I see, I'll remove Failsafe from the name - we dont need it here.

2021-11-29 11:48 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/FetchConfiguration.java
> +        OsmConnection connection = new OsmConnection(openstreetmapApiUrl, "user-agent", null);
From the tests which we executed it may be also "dummy" "or-whatever" so for now I would stay with that. Going to config with that parameter is superfluous action

2021-11-29 11:49 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/FailsafeOsmFetchClient.java
> +        return Failsafe.with(RetryPolicyFactory.getClientConnectionRetryPolicy())
For now on, we only experienced exception which are mentioned in class `RetryPolicyFactory` - other were not yet experienced so the question is if we should not wait for its first occurence?

2021-11-29 14:25 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/model/WayViolation.java
> +public class WayViolation {
I think I'll rename it to `ViolatingWayWithParentRelations` to make it more straightforward

2021-11-30 08:51 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmose/model/DoubleInnerPolygonViolation.java
> +public class DoubleInnerPolygonViolation {
Thats literally the name of violation which comes from osmose, but I agree that duplicated sounds better. Lets change it

2021-11-30 09:27 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/store/StoreConfiguration.java
> +    MapDataApi getWriteDataApi(String token, String tokenSecret, String consumerKey, String consumerSecret, String openstreetmapApiUrl) {
Mainly we're not allowing reader to have editing auth.

2021-11-30 09:34 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmose/model/DoubleInnerPolygonViolation.java
> +package com.tomtom.maps.osm.innerringbot.osmose.model;
It's an osmose thing and generally the output type of `osmose` package, I thought that having it in separate `model` package makes it easier to understand purpose of all classes (right now we have 1 public class per all packages except model/utils and I liked it)

2021-11-30 13:11 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/OsmDataFetcher.java
> +            log.warn("Incomplete data for violation relation id {} and way ids {}", violation.getViolatingRelationId(), violation.getPairOfViolatingWaysIds());
Its impossible to get 3 ways here since we're only fetching 2 ways and 1 relation, so that warning message is ok.

2021-11-30 13:32 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/store/ChangesUploader.java
> +        log.info("Changeset id {} has been closed", changesetId);
Granularity should be ok here. 

We went with approach of uploading pairs of fixes related to single violation together - so if any of these 2 edits fails then we skip such violation completely. Rest of the violations in that changeset will still be processed and I think that approach is ok - we still want to put many violations per changeset and we dont want to skip whole changeset if only 1 violation fails to update.

2021-11-30 14:24 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/SourceVerifier.java
> +                log.warn("Source tag value is present but its value: {} is other than configured for violation {}", relationSourceTagValue.get(), violatingOsmData);
This warning contains all feature ids of the violation already. It might be useful for analysis.

2021-11-30 14:33 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/VerifierConfiguration.java
> +            @Value("#{'${run.parameters.verifier.source.tag-values}'.split(',')}") Collection<String> sourceTagValues) {
Actually we've spent some time trying to do it without split, but had some problems with making it work with @Value and left it like that to not waste more time. We'll get back to it if there is some spare time

2021-11-30 14:37 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/resources/application-dev.yml
> +        tag-values: CanVec 6.0 - NRCan,CanVec 8.0 - NRCan
That's related to comment with @Value problem and using .split

2021-11-30 14:39 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/FailsafeOsmFetchClient.java
> +        return Failsafe.with(RetryPolicyFactory.getClientConnectionRetryPolicy())
isn't that kinda like waiting to actually get an exception before you write a `try`/`catch`?
I'd say let's prepare ourselves for all reasonable problems, potential ones included
"I don't think this problem is worth safeguarding against" is a better argument than "we haven't seen it fail this exact way yet"

2021-12-01 08:45 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/store/ChangesUploader.java
> +        long changesetId = failsafeOsmWriteClient.openChangeset(CHANGESET_TAGS);
Right now according to documentation changesets autocloses 1 hour after last edit made to it. Given our 50 violations per changeset plan something would need to go very bad for changeset to be closed before we finish all uploading all violations and if it does go wrong there won't be problems with split changes for each violation (we're uploading fixes in pairs already).

I think i would prefer to leave it like that for first runs and see how tool behaves, we don't risk corrupting the data and I'm afraid that if we put some logic of creating new changesets in case of auto-close we might end up creating a lot more changesets than we initially planned (and we know that community doesn't want that too).

2021-12-01 12:11 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/OsmDataFetcher.java
> +        return Optional.empty();
After brain storming of that case we came to the conclusion that we will use `findAny`. The worst case scenario is that two ways provided in OSMOSE violations belongs to the same relation but such a case will be filtered out by verifiers.

2021-12-01 12:22 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/model/ViolatingOsmData.java
> +        return String.format("(relationId=%d, innerRingWayId=%d, duplicatingWayId=%d)",
Logging info has beed updated - please check them one more time.

2021-12-01 12:46 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/VerifierBase.java
> +    private final boolean active;
At this moment we `SourceVerifier` which is optional - configurable by the user. 
So we see two options (check if user provide tags as parameter and if yes include this verifier otherwise not include it) or introduce a flag which would say if verifier should be included. (If you see any other option let us know). 
Why we choose this solution - when spoke with Ania, she told us about verifiers and maybe we will need in future to turn off some of them. Having such flag is easy to configure that.

2021-12-01 13:33 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/VerifierBase.java
> +    private final boolean active;
`ConditionalOnProperty` has been implemented so this filed is superfluous.

2021-12-01 13:40 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/ClosedInnerRingVerifier.java
> +        return true;
You are right but the method is called `wayIsNotClosed`, so if way has only one node we treat it as not closed and violation with such a way is discarded for further processing.

2021-12-01 13:51 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/HasSameNodesVerifier.java
> +        return wayNodes.get(0).equals(wayNodes.get(wayNodes.size() - 1));
You really read it :) Only two occurrences but You read :) it so we extracted to separated util class

2021-12-01 14:19 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/OsmDataFetcher.java
> +        if (isViolationDataFetched(osmWays, osmRelation)) {
Renaming the method to `isViolationDataConsistent`

2021-12-01 14:53 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/HasSameNodesVerifier.java
> +        boolean areWaysDrawnInTheSameDirection = hasTheSameNodes(duplicatedRelationMemberNodes, wayPotentialRelationMember);
USB algorithm - LOL

2021-12-01 15:55 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmose/model/DoubleInnerPolygonViolation.java
> +    int osmoseRuleId;
added validation in `OsmoseViolationsValidator`

2021-12-02 07:31 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/VerifierConfiguration.java
> +            @Value("#{'${run.parameters.verifier.source.tag-values}'.split(',')}") Collection<String> sourceTagValues) {
Yes, Spring supports collections in parameters but YAML does not do it. You may provide `[string1, string2]` as yaml paramer but then You need to create only for that one filed a configuration class because  only then `data bind` mechanism will be used. We are not using this mechanism so we need to provide them as we did - separate by coma.
We could resign from `Collection<String>` and use `String[]` instead but then we should convert array to a collection/list.
IMHO, for not it is good engough

2021-12-02 07:31 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/resources/application-dev.yml
> +        tag-values: CanVec 6.0 - NRCan,CanVec 8.0 - NRCan
As in above comment about parameters slit.

2021-12-02 07:35 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/resources/application-dev.yml
> +    path-to-violations-file: "C:\\Data\\OSMOSE\\violations.json"
The example path was provided in `application-dev` profile, so if the user make enough effort to run application with profile then also He should be able to change the path to file. But ok.. probably I see You point of view.. will change it to "violations_file_path"

2021-12-02 07:42 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/resources/application-dev.yml
> +    openstreetmap-api-url: "https://api.openstreetmap.org/api/0.6/"
For now I would leave it, and in the moment when url of dev env is known we may change it.

2021-12-02 07:48 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/utils/TestFeatureGenerator.java
> +                .orElse(defaultValue);
ok

2021-12-02 07:55 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/utils/TestFeatureGenerator.java
> +    public static WayViolation buildWayViolation(
auto-refactor completed.

2021-12-02 07:55 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/ClosedInnerRingVerifierTest.java
> +    //  Should ways be always only polygons - closed ways ?? first node == last node
removed

2021-12-02 08:21 UTC, ArkadiuszMaciaszczyk-TomTom submitted a review, later dismissed

2021-12-02 08:50 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/resources/logback-spring.xml
> +    <logger name="com.tomtom.maps.osm.innerringbot" level="debug" additivity="false">
ok, we log debug only to files.

2021-12-02 08:54 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/TestCaseGenerator.java
> +            long violatingRelationId,
We not always need this id in tests so setting it as `NonNull` would affect to always provide it - even if test case doesn't require it. I would leave it as it is.

2021-12-02 08:58 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/changes/ChangesGenerator.java
> +    private OsmDataChange generateChange(ViolatingOsmData violatingOsmData) {
So many men so many opinions about naming proposes :) 
After short brainstorm we change class name.

2021-12-02 09:06 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmapi/changes/ChangesGeneratorTest.java
> +        Relation relation = buildRelation(DEFAULT_ID_VALUE);
ok, nice idea

2021-12-02 09:09 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/FailsafeOsmFetchClientTest.java
> +    final static long DEFAULT_ID = 10633691L;
ok, done :)

2021-12-02 09:13 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/FailsafeOsmFetchClientTest.java
> +        Way way = new OsmWay(DEFAULT_ID, 1, List.of(), Map.of());
It is a proof Dear Sherlock :) corrected :)

2021-12-02 09:17 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/FailsafeOsmFetchClientTest.java
> +                .getWay(DEFAULT_ID);
Yes we can do that :) done :)

2021-12-02 09:18 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/FailsafeOsmFetchClientTest.java
> +        Relation relation = new OsmRelation(DEFAULT_ID, 1, List.of(), Map.of());
it conflicts with above comment. Right now this objects are already used, so there is no need to exchange them by Mocks

2021-12-02 09:39 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmapi/store/FailsafeOsmWriteClientTest.java
> +class FailsafeOsmWriteClientTest {
done

2021-12-02 09:40 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmose/ViolationJsonReaderTest.java
> +        Path jsonPath = Paths.get("src", "test", "resources", "exampleOsmoseViolation.json");
We would stay with our propose.

2021-12-02 09:44 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/ClosedInnerRingVerifierTest.java
> +                                .verifierResult(false),
We like that conditions are explicitly presented. We propose to leave it

2021-12-02 09:56 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/SourceVerifierTest.java
> +        )
Noble idea, implemented.

2021-12-02 10:21 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/SourceVerifierTest.java
> +    private static final Map<String, String> EXAMPLE_SOURCE_TAG_2 = Map.of("source", EXAMPLE_SOURCE_VALUE_2);
But we would still need to specify "source" everywhere -e.g. `.relationTag("source",EXAMPLE_SOURCE_VALUE_1)`. 
I think I prefer to have these `Map.of` constants. However I'll add `@Singular` to these 2 constants related to list, so we can get rid of them.

2021-12-02 10:22 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/SourceVerifierTest.java
> +    private static final String EXAMPLE_SOURCE_VALUE_2 = "CanVec 10.0 - NRCan";
I'll go with `SOURCE_1`, I like that short version.

2021-12-02 10:27 UTC, ArkadiuszMaciaszczyk-TomTom approved these changes

2021-12-02 10:49 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/SourceVerifierTest.java
> +                TestCaseGenerator.sourceVerifierTestCase()
After name changes, adding few cases and some minor rearrangements I think its good enough. Thanks for suggestions

2021-12-02 11:08 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/DuplicatingWayHasTagsVerifierTest.java
> +                                .duplicatingWayTags(Map.of())
We decided its good enough like now

2021-12-02 11:19 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/DuplicatingWayIsNotMemberOfAnyRelationVerifierTest.java
> +                                .name("Other way, that does not belong to any relation should pass verification")
Indeed we didnt refactor the test case names after we changed the class names. Thanks for noticing, we corrected it.

2021-12-02 11:31 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/HasSameNodesVerifierTest.java
> +                )
We added this test case, however with `verifierResult(true)`. These ways have the same nodes, but different order, so it should pass. We don't care if these ways closed or not in this verifier (different one checks that)

2021-12-02 11:37 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/HasSameNodesVerifier.java
> +class HasSameNodesVerifier extends VerifierBase {
Im impressed by your analysis :P 
we changed the name to `WaysHaveMatchingNodesVerifier`

2021-12-02 11:39 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/InnerRingWayIsOnlyMemberOfViolatingRelationVerifierTest.java
> +    public static Stream<Arguments> getTestCases() {
We had by mistake added here tags for duplicatingWay instead of innerRingWay. Fixed it.

2021-12-02 11:42 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/SourceVerifierTest.java
> +                        .sourceTagValues(EXAMPLE_TAG_VALUES_1)
We'll keep it as it is.

2021-12-02 11:53 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/FetchConfiguration.java
> +    OsmDataFetcher getOsmDataFetcher(@NonNull @Value("${run.parameters.openstreetmap-api-url:#{null}}") String openstreetmapApiUrl) {
We'll probably add a task to add some kind of parameter validator. For now app will just crash with IllegalState/NullPointer exceptions

2021-12-02 12:40 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/OsmDataFetcher.java
> +    private Optional<ViolatingOsmData> createViolatingOsmData(List<Way> osmWays, Relation osmRelation) {
You are right it would introduce simplification - we create a task for that refactor it in next step. But for now lets not complicate this PR and go on with what is proposed

2021-12-02 12:49 UTC, ArkadiuszMaciaszczyk-TomTom approved these changes

2021-12-02 13:10 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/HasSameNodesVerifier.java
> +        return wayWithoutClosingNode;
Nice improvement - thanks for that. The previous version was to ensure that we do not modifying original list but your propose is very good!!

2021-12-02 13:25 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/FailsafeOsmFetchClient.java
> +        return Failsafe.with(RetryPolicyFactory.getClientConnectionRetryPolicy())
There is default 45s timeout on OsmConnection class so we should not experience hangouts or frozen connection

2021-12-02 17:06 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/store/ChangesUploader.java
> +        log.info("Changeset id {} has been closed", changesetId);
by pairs of fixes I assume you mean "adding tags to inner way" and "removing duplicated way"?
are we uploading them in a transactional way?
because if the first half of violation fails and we skip uploading the second half, then it's fine
but if the first half of the fix succeeds but the second half fails, then we can't just leave the violation half-fixed in osm

2021-12-02 17:13 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/ClosedInnerRingVerifier.java
> +        return true;
we can skip this one for now

2021-12-02 17:13 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmose/model/DoubleInnerPolygonViolation.java
> +package com.tomtom.maps.osm.innerringbot.osmose.model;
:+1:, got resolved as suggested

2021-12-02 17:21 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/verifiers/VerifierConfiguration.java
> +            @Value("#{'${run.parameters.verifier.source.tag-values}'.split(',')}") Collection<String> sourceTagValues) {
we can skip this for now, but let's come back to this later

2021-12-02 17:22 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/resources/application-dev.yml
> +    openstreetmap-api-url: "https://api.openstreetmap.org/api/0.6/"
we can skip this for now

2021-12-02 17:24 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/utils/TestFeatureGenerator.java
> +    public static OsmRelation buildRelation(Long violatingRelationId, Map<String, String> tags) {
we can skip this for now

2021-12-02 17:44 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/FailsafeOsmFetchClientTest.java
> +        Relation relation = new OsmRelation(DEFAULT_ID, 1, List.of(), Map.of());
you could mock the item only to get an instance without mocking any behaviors of that mocked instance
then, instead of using `isEqualTo` that looks at the content, you can use `isSameAs` that checks object references
```java
        //  given
        Relation relation = mock(OsmRelation.class);
        when(mapDataApi.getRelation(FEATURE_ID))
                .thenThrow(OsmConnectionException.class)
                .thenReturn(relation);

        //  when
        Relation actualRelation = osmFetchClient.getRelation(FEATURE_ID);

        //  then
        verify(mapDataApi, times(2))
                .getRelation(FEATURE_ID);
        assertThat(actualRelation).isSameAs(relation);
```

2021-12-02 18:24 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/HasSameNodesVerifierTest.java
> +                )
> We don't care if these ways closed or not in this verifier (different one checks that)

well, if this check is supposed to check if two ways have the same geometry, then you might want to start caring because closed and open way reacts differently to shifting the node order
as far as I can tell, splitting off checking if the way is closed to a separate verifier means that `WaysFormClosedRingsVerifier` is useful only to let us start the processing with the simplest cases

2021-12-02 18:43 UTC, MaciejMyczkowski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/innerringbot/osmapi/fetch/FailsafeOsmFetchClient.java
> +        return Failsafe.with(RetryPolicyFactory.getClientConnectionRetryPolicy())
we can skip this for now, but do look into that in the meantime

2021-12-03 08:38 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/osmapi/store/ChangesUploader.java
> +        log.info("Changeset id {} has been closed", changesetId);
Yes, by pairs i mean "adding tags to inner way" and "removing duplicating way". 
It's also transactional -
MapdataApi `uploadChanges` method puts all elements into single POST request and according to OSM Wiki of this `changeset/id/upload` endpoint - `This is guaranteed to be running in a transaction. So either all the changes are applied or none.`.

2021-12-03 08:48 UTC, ArkadiuszMaciaszczyk-TomTom submitted a review, later dismissed

2021-12-03 08:56 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/FailsafeOsmFetchClientTest.java
> +        Relation relation = new OsmRelation(DEFAULT_ID, 1, List.of(), Map.of());
Nice, i like it.

2021-12-03 08:57 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/com/tomtom/maps/osm/innerringbot/utils/RetryPolicyFactory.java
> +    public <T> RetryPolicy<T> getClientConnectionRetryPolicy() {
Timeout has been added.

2021-12-03 08:57 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/OsmDataFetcherTest.java
> +        fetchClient = new FailsafeOsmFetchClient(new MapDataApi(new OsmConnection("https://api.openstreetmap.org/api/0.6/", "agent", null)));
we've put it to configuration yaml in tests.

2021-12-03 08:58 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/OsmDataFetcherTest.java
> +        long duplicatingWayId = 148813181L;
Task for OsmDataFetcher refactor has been created. For this PR we keep it as now

2021-12-03 08:59 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/osmapi/fetch/OsmDataFetcherTest.java
> +class OsmDataFetcherTest {
Task for refactor of OSmDataFetcher has been created. For now we keep it as now.

2021-12-03 09:29 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/HasSameNodesVerifierTest.java
> +                )
After some discussion we decided to indeed check in 1 verifier if ways are closed and if nodes are the same (despite the ordering) :)

2021-12-03 09:39 UTC, ArkadiuszMaciaszczyk-TomTom submitted a review, later dismissed

2021-12-03 09:50 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/ClosedInnerRingVerifierTest.java
> +                                .name("Both ways have closing nodes")
As we discussed yesterday It would make it more readable but we decided to leave it as it is

2021-12-03 09:53 UTC, LukaszStaszewski-TomTom commented on bot-double-inner-ring/src/test/java/com/tomtom/maps/osm/innerringbot/verifiers/ClosedInnerRingVerifierTest.java
> +    void shouldVerifyIfWaysHaveClosingNode(
We decided to stick with current approach

2021-12-03 10:13 UTC, ArkadiuszMaciaszczyk-TomTom approved these changes

2021-12-03 11:15 UTC, ArkadiuszMaciaszczyk-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/rings/inner/duplicates/osmapi/store/OsmFixUploader.java
> +            "osm_wiki_documentation_page", "https://wiki.openstreetmap.org/wiki/Automated_edits/TTmechanicalupdates/Fix_issue_with_duplicated_inner_polygons_in_Canada");
Do we already have discussion link? Why did you remove discussion placeholder?

2021-12-03 11:18 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/rings/inner/duplicates/osmapi/store/OsmFixUploader.java
> +            "osm_wiki_documentation_page", "https://wiki.openstreetmap.org/wiki/Automated_edits/TTmechanicalupdates/Fix_issue_with_duplicated_inner_polygons_in_Canada");
Right now we don't have it, but we're working on it. We planned to add a task to make it configurable - since the discussion link will be different in each country.

2021-12-03 11:20 UTC, ArkadiuszMaciaszczyk-TomTom submitted a review, later dismissed

2021-12-03 13:12 UTC, KamilLucki-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/rings/inner/duplicates/ViolationsFixer.java
> +        List<ViolatingOsmData> allViolatingData = osmoseViolations.stream()
It looks good, but can be better, after moving these streams to separate methods

2021-12-03 13:15 UTC, KamilLucki-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/rings/inner/duplicates/osmapi/fetch/FetchConfiguration.java
> +    MapDataApi getReadMapDataApi(String openstreetmapApiUrl) {
I think this method can be private

2021-12-03 13:18 UTC, KamilLucki-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/rings/inner/duplicates/osmapi/fetch/OsmDataFetcher.java
> +            }
looks good, but it would be more readable for me, if this was moved to separate method

2021-12-03 13:28 UTC, KamilLucki-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/rings/inner/duplicates/verifiers/SourceVerifier.java
> +    boolean isMatchingVerifierCriteria(ViolatingOsmData violatingOsmData) {
I think this method has logic nested a bit too much. Please refactor if possible

2021-12-03 13:30 UTC, KamilLucki-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/rings/inner/duplicates/verifiers/Verifier.java
> +    public boolean test(ViolatingOsmData violatingOsmData) {
I think `@Override` is missing

2021-12-03 13:34 UTC, KamilLucki-TomTom commented on bot-double-inner-ring/src/main/resources/application-dev.yml
> +        tag-values: NRCan-CanVec-10.0,NRCan-CanVec-8.0,NRCan-CanVec-7.0,CanVec 6.0 - NRCan
Is there a difference in behaviour between this and `[ "NRCan-CanVec-10.0","NRCan-CanVec-8.0","NRCan-CanVec-7.0","CanVec 6.0 - NRCan" ]` from application.yml

2021-12-03 13:34 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/resources/application-dev.yml
> +        tag-values: NRCan-CanVec-10.0,NRCan-CanVec-8.0,NRCan-CanVec-7.0,CanVec 6.0 - NRCan
No, this is a leftover from previous way of providing source values - i'll remove it. good catch :)

2021-12-03 13:35 UTC, KamilLucki-TomTom commented on bot-double-inner-ring/src/test/java/osm/bots/rings/inner/duplicates/osmapi/fetch/OsmDataFetcherTest.java
> +        //given
really minor, but in other tests there is an space immediately after `//` like `// given`

2021-12-03 13:37 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/resources/application-dev.yml
> +        tag-values: NRCan-CanVec-10.0,NRCan-CanVec-8.0,NRCan-CanVec-7.0,CanVec 6.0 - NRCan
Actually we'll remove -dev profile, we dont really use it right now.

2021-12-03 13:41 UTC, KamilLucki-TomTom commented on bot-double-inner-ring/src/test/java/osm/bots/rings/inner/duplicates/utils/PartitionTest.java
> +class PartitionTest {
Tests in this class are missing `given when then` comments, it would be nice to add it here, to be consistent.

2021-12-03 13:49 UTC, KamilLucki-TomTom approved these changes

2021-12-03 14:13 UTC, KamilLucki-TomTom approved these changes

2021-12-03 14:13 UTC, BartoszChrominski-TomTom commented on bot-double-inner-ring/src/main/java/osm/bots/rings/inner/duplicates/verifiers/SourceVerifier.java
> +    boolean isMatchingVerifierCriteria(ViolatingOsmData violatingOsmData) {
I've refactored it a little, it might need some more attention in the future, but for now it should be ok

2021-12-03 14:27 UTC, ArkadiuszMaciaszczyk-TomTom approved these changes

2021-12-06 12:59 UTC, closed without merging